import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

// Components
import UserAppTour from "@/components/UserAppTour";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html
            lang="en"
            className="h-full bg-gray-900">
            <body className={`${inter.className} h-full`}>
                <UserAppTour>{children}</UserAppTour>
            </body>
        </html>
    );
}
