"use client";

import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

// Deps
import { useState } from "react";

// Components
import SideBar from "@/components/SideBar";
import SearchHeader from "@/components/SearchHeader";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    const [sidebarOpen, setSidebarOpen] = useState(false);
    return (
        <html
            lang="en"
            className="h-full bg-gray-900">
            <body className={`${inter.className} h-full`}>{children}</body>
        </html>
    );
}
